### PR TITLE
[READY] add rest-api sites

### PR DESCRIPTION
**Pull request by baylanger**
I went ahead and look for search for rest-api sites.  Some sites might require client certificates, if SSL handshake fails, workers should not run.

Notes:

These 3 sites currently aren't reachable - same goes for their respective "www" host.  I left them in the file, it is possible some sites don't use standard port 443 - need to hunt them down!

```
api.e-portal.ru
api.kartoteka.ru
api.cit-ufa.ru
```

Email provider entities to bad actors :
```
lenta.ru MX => inmx.rambler.ru. => www.rambler.ru, api.rambler.ru, etc
gazeta.ru MX => inmx.rambler-co.ru => www.rambler-co.ru
```
www.rambler.ru & api.rambler.ru were added in this PR but if there's a need to remove them, let me know.

Below "diff -b" output.

```
$ git diff -b HEAD^
diff --git a/internal/stoppropaganda/websites.go b/internal/stoppropaganda/websites.go
index 63391d9..94d4eef 100644
--- a/internal/stoppropaganda/websites.go
+++ b/internal/stoppropaganda/websites.go
@@ -19,11 +19,13 @@ var targetWebsites = map[string]struct{}{

        "https://bukimevieningi.lt": {},
        "https://musutv.lt":         {},
+       "https://api.musutv.lt":     {},
        "https://baltnews.lt":       {},
        "https://lt.rubaltic.ru":    {},
        "http://sputniknews.lt":     {},
        "https://lv.sputniknews.ru": {},
        "https://viada.lt":          {},
+       "https://api.viada.lt":      {},

        /* Russia */

@@ -33,11 +35,15 @@ var targetWebsites = map[string]struct{}{
        "https://ria.ru/lenta":       {},
        "https://www.rbc.ru":         {},
        "https://www.rt.com":         {},
+       "https://api.rt.com":         {},
        "https://smotrim.ru":         {},
+       "https://api.smotrim.ru":     {},
        "https://tass.ru":            {},
+       "https://api.tass.ru":        {},
        "https://tvzvezda.ru":        {},
        "https://vsoloviev.ru":       {},
        "https://www.1tv.ru":         {},
+       "https://api.1tv.ru":         {},
        "https://www.vesti.ru":       {},
        "https://zakupki.gov.ru":     {},
        "https://er.ru":              {},
@@ -52,11 +58,14 @@ var targetWebsites = map[string]struct{}{
        "https://www.gazeta.ru":      {},
        "https://www.kp.ru":          {},
        "https://riafan.ru":          {},
+       "https://api.riafan.ru":      {},
        "https://pikabu.ru":          {},
+       "https://api.pikabu.ru":      {},
        "https://www.kommersant.ru":  {},
        "https://omk.ru":             {},
        "https://www.yaplakal.com":   {},
        "https://bezformata.com":     {},
+       "https://api.bezformata.com": {},
        "https://regnum.ru":          {},
        "https://eadaily.com":        {},
        "https://www.rubaltic.ru":    {},
@@ -74,28 +83,35 @@ var targetWebsites = map[string]struct{}{
        "https://www.severstal.com":                 {},
        "https://www.metalloinvest.com":             {},
        "https://nangs.org":                         {},
+       "https://api.nangs.org":                     {},
        "https://rmk-group.ru/ru":                   {},
        "https://www.tmk-group.ru":                  {},
        "https://ya.ru":                             {},
+       "https://any.yandex.ru":                     {},
        "https://www.polymetalinternational.com/ru": {},
        "https://www.uralkali.com/ru":               {},
        "https://www.eurosib.ru":                    {},
+        "https://www.rambler.ru":                    {},

        // Banks
        "https://www.sberbank.ru":                          {},
        "https://online.sberbank.ru":                       {},
-       "https://www.vtb.ru":                               {},
-       "https://www.gazprombank.ru":                       {},
        "https://api.developer.sber.ru/product/SberbankID": {},
        "https://api.sberbank.ru/prod/tokens/v2":           {},
        "https://api.sberbank.ru/prod/tokens/v2/oauth":     {},
        "https://api.sberbank.ru/prod/tokens/v2/oidc":      {},
+       "https://www.vtb.ru":                               {},
+       "https://api.vtb.ru":                               {},
+       "https://www.gazprombank.ru":                       {},
+       "https://api.gazprombank.ru":                       {},
        "https://www.moex.com":                             {},
+       "https://api.moex.com":                             {},
        "http://www.fsb.ru":                                {},

        //The state
        "https://gosuslugi.ru":         {},
        "https://www.mos.ru/uslugi":    {},
+       "https://api.mos.ru":           {},
        "http://kremlin.ru":            {},
        "http://en.kremlin.ru":         {},
        "http://government.ru":         {},
@@ -123,10 +139,14 @@ var targetWebsites = map[string]struct{}{

        // Exchanges connected to russian banks
        "https://cleanbtc.ru":           {},
+       "https://api.cleanbtc.ru":       {},
        "https://bonkypay.com":          {},
        "https://changer.club":          {},
+       "https://api.changer.club":      {},
        "https://superchange.net":       {},
+       "https://api.superchange.net":   {},
        "https://mine.exchange":         {},
+       "https://api.mine.exchange":     {},
        "https://platov.co":             {},
        "https://ww-pay.net":            {},
        "https://delets.cash":           {},
@@ -135,6 +155,7 @@ var targetWebsites = map[string]struct{}{
        "https://coinpaymaster.com":     {},
        "https://bitokk.biz":            {},
        "https://www.netex24.net":       {},
+       "https://api.netex24.net":       {},
        "https://cashbank.pro":          {},
        "https://flashobmen.com":        {},
        "https://abcobmen.com":          {},
@@ -148,10 +169,13 @@ var targetWebsites = map[string]struct{}{

        // Electronic signature services
        "https://iecp.ru":             {},
+       "https://api.iecp.ru":         {},
        "https://uc-osnovanie.ru":     {},
+       "https://api.uc-osnovanie.ru": {},
        "http://www.nucrf.ru":         {},
        "http://www.belinfonalog.ru":  {},
        "http://www.roseltorg.ru":     {},
+       "https://api.roseltorg.ru":    {},
        "http://www.astralnalog.ru":   {},
        "http://www.nwudc.ru":         {},
        "http://www.center-inform.ru": {},
@@ -160,10 +184,12 @@ var targetWebsites = map[string]struct{}{
        "http://www.ucpir.ru":         {},
        "http://dreamkas.ru":          {},
        "http://www.e-portal.ru":      {},
+       "https://api.e-portal.ru":     {},
        "http://izhtender.ru":         {},
        "http://imctax.parus-s.ru":    {},
        "http://www.icentr.ru":        {},
        "http://www.kartoteka.ru":     {},
+       "https://api.kartoteka.ru":    {},
        "http://rsbis.ru":             {},
        "http://www.stv-it.ru":        {},
        "http://www.crypset.ru":       {},
@@ -179,9 +205,11 @@ var targetWebsites = map[string]struct{}{
        "http://www.otchet-online.ru": {},
        "http://udcs.ru":              {},
        "http://www.cit-ufa.ru":       {},
+       "http://api.cit-ufa.ru":       {},
        "http://elkursk.ru":           {},
        "http://www.icvibor.ru":       {},
        "http://ucestp.ru":            {},
+       "https://api.ucestp.ru":       {},
        "http://mcspro.ru":            {},
        "http://www.infotrust.ru":     {},
        "http://epnow.ru":             {},
@@ -208,6 +236,7 @@ var targetWebsites = map[string]struct{}{
        "https://www.belapb.by":                   {},
        "https://bankdabrabyt.by":                 {},
        "https://belinvestbank.by/individual":     {},
+       "https://api.belinvestbank.by/":           {},

        // by business
        "https://bgp.by/ru":           {},
@@ -227,6 +256,7 @@ var targetWebsites = map[string]struct{}{
        "https://ont.by":                {},
        "https://www.024.by":            {},
        "https://www.belnovosti.by":     {},
+       "https://api.belnovosti.by":     {},
        "https://mogilevnews.by":        {},
        "https://yandex.by":             {},
        "https://www.slonves.by":        {},
@@ -235,10 +265,13 @@ var targetWebsites = map[string]struct{}{
        "https://radiusfm.by":           {},
        "https://alfaradio.by":          {},
        "https://radiomir.by":           {},
+       "https://api.radiomir.by":       {},
        "https://radiostalica.by":       {},
        "https://radiobrestfm.by":       {},
+       "https://api.radiobrestfm.by":   {},
        "https://www.tvrmogilev.by":     {},
        "https://minsknews.by":          {},
+       "https://api.minsknews.by":      {},
        "https://zarya.by":              {},
        "https://grodnonews.by":         {},
 }
```

DNS lookup output
```
api.musutv.lt 192.0.78.2
api.viada.lt 92.61.37.66
api.rt.com 89.191.237.181
api.smotrim.ru 178.248.232.222
api.tass.ru 82.202.190.72
api.1tv.ru 178.248.233.188
api.riafan.ru 185.41.161.107
api.pikabu.ru is an alias for lb.pikabu.ru
api.yaplakal.com 172.64.80.1
api.bezformata.com 172.67.74.105
api.nangs.org 185.178.208.143
api.ya.ru is an alias for any.yandex.ru.
api.sberbank.ru 185.157.96.191
api.vtb.ru 217.14.58.16
api.gazprombank.ru 195.225.38.209
api.moex.com 85.118.181.22
api.mos.ru 212.11.155.150
api.cleanbtc.ru 185.178.208.151
api.changer.club 172.64.80.1
api.superchange.net 172.64.80.1
api.mine.exchange 190.115.19.114
api.netex24.net 51.104.139.247
api.iecp.ru 185.179.199.8
api.uc-osnovanie.ru 185.71.67.237
api.roseltorg.ru 185.79.118.2
api.e-portal.ru 195.162.53.10
api.kartoteka.ru 178.57.94.100
api.kt-69.ru 217.107.219.57
api.cit-ufa.ru 185.26.122.4
api.ucestp.ru 85.119.149.95
api.belinvestbank.by 194.62.64.140
api.belnovosti.by 93.84.112.130
api.yandex.by is an alias for any.yandex.ru
api.radiomir.by 178.124.138.89
api.radiobrestfm.by 178.124.138.66
www.rambler.ru 81.19.82.98
```

Some sites might point to a local netblock, I didn't filter.

### CODE REVIEW

**Comment by baylanger** [comment]
Do not merge.. I resolved the conflict using GitHub UI but now I see alignment issues :(

Will fix later.

**Comment by erkexzcx** [comment]
Yes, please resolve merge conflicts. :pray:

**Comment by baylanger** [comment]
@erkexzcx this is ready to merge - looks like I moved some sites to re-group them together?!

**Comment by baylanger** [comment]
I've got other things to do - but later I will cross-check again to made sure I didn't remove anything by accident while fixing conflicts... we don't want to remove nobody :D

**Pull request merged**
