### PR TITLE
Added Education category and websites

### PR DESCRIPTION
**Pull request by 8FBjGl4k77**
Added an  "Education" category and "school.mos.ru", "uchi.ru", "resh.edu.ru" in it.

### CODE REVIEW

**Comment by erkexzcx** [comment]
Do these education organizations teach education, or propaganda?

**Comment by Ycirn** [comment]
This guy tried updating this on the https://github.com/ajax-lives/NoRussian repo as well. We denied it. Hitting schools will only cause issues to students, not the government.

**Comment by erkexzcx** [comment]
> Hitting schools will only cause issues to students, not the government.

Agree. Education has nothing to do with it, except if they publicitly encourage Russian aggression towards Ukraine. I will close this MR.

**Comment by 8FBjGl4k77** [comment]
Sorry man, im just a student trying to make my life a bit easier by causing trouble.

**Pull request closed without merging**
