### PR TITLE
Updated targets

### PR DESCRIPTION
**Pull request by FluxState**
* Added targets from ITA UA.
* Removed changed IPs.
* Removed guarded entries (cf, ddos guard, etc.)

In case this repository is not updated anymore, see https://github.com/FluxState/stoppropaganda/tree/updated-targets

### CODE REVIEW

**Comment by deputinizer** [comment]
```
--- FAIL: TestDNSTargets (0.00s)
    dns_test.go:11: Invalid DNS target '193.148.44.179'
    dns_test.go:11: Invalid DNS target '195.161.53.77'
    dns_test.go:11: Invalid DNS target '195.161.52.77'
    dns_test.go:11: Invalid DNS target '193.148.44.180'
    dns_test.go:11: Invalid DNS target '195.209.181.8'
    dns_test.go:11: Invalid DNS target '185.170.2.237'
    dns_test.go:11: Invalid DNS target '95.173.128.77'
    dns_test.go:11: Invalid DNS target '94.124.200.34 '
    dns_test.go:11: Invalid DNS target '185.170.3.237'
    dns_test.go:11: Invalid DNS target '195.209.134.8'
--- FAIL: TestWebsitesLinks (0.00s)
    websites_test.go:13: Invalid website 'https://topcor.ru/': ends with slash
    websites_test.go:13: Invalid website 'https://orders.roseltorg.ru/': ends with slash
    websites_test.go:13: Invalid website 'https://www.chechnya.online/ru/': ends with slash
    websites_test.go:42: duplicate websites 'https://www.es.pfrf.ru' and 'https://es.pfrf.ru'
    websites_test.go:13: Invalid website 'http://fss.gov.ru/': ends with slash
    websites_test.go:42: duplicate websites 'https://www.avito.ru' and 'https://avito.ru'
    websites_test.go:13: Invalid website 'https://rosseti.roseltorg.ru/': ends with slash
FAIL
```

**Comment by FluxState** [comment]
@deputinizer How do you run the tests?

**Comment by deputinizer** [comment]
Good. Looks like @erkexzcx was kidnapped by Russians 9 days ago :smiley: so he can't merge your commits :wink:

**Comment by erkexzcx** [comment]
I am still here. :) I will check this MR soon.

**Comment by erkexzcx** [comment]
@FluxState Hey. Would you like to become owner of this repo? I can transfer it for you since I am no longer activelly maintaining it.

**Pull request merged**
