### PR TITLE
add externalized data

### LINKED ISSUE #34: externalize list of target sites so that we can use them for other tools as well
https://github.com/droopy4096/agressor-sites has JSON versions of similar kind... also would make it easier to contribute more targets (eliminate obsolete ones)

### PR DESCRIPTION
**Pull request by droopy4096**
resolves https://github.com/erkexzcx/stoppropaganda/issues/34

### CODE REVIEW

**Comment by erkexzcx** [comment]
No, downloading data separately is inconvenience. Consider including those files into a binary, otherwise I will not merge this.

See https://stackoverflow.com/a/65148366

**Comment by baylanger** [comment]
The list is becoming very long, what if we add for each site what "type" of site it is.

For example:

gov/city/military, media, bank, oligarch (personal web site?), petrol/gaz/electricity, isp (internet sec providers), tv, radio, news, mobile phone provider, transportation company (truck or bus), air lines/airports, etc.

Sorry I just let go myself 👯 

In near future, could one of these options be useful?  I think so.

```
-dos_list="gov,mil,oligarch"
-dos_name="sberbank,gazprom"
```

Target a specific "list" of entities or target specific sites based on name.  The second one can be implemented now but the first one requires creating ... multiple list or ?

Fantastic project !

**Comment by droopy4096** [comment]
@erkexzcx will take a look, however as @baylanger pointed out lists are growing so we need to adapt at runtime. I can add option to point to external JSON in addition to baked-in list, would that work?

**Comment by erkexzcx** [comment]
Right, so let's figure out few things.

1. What is the actual use case? How does other "products" would use these centralized lists? Are we talking programming language agnostic solutions?

2. In what format would you like to store those lists? Would YAML be sufficient? :)

These are the only requirements for this app:
1. My app would never use external & centralized list of domains as this would clearly become a **killswitch**.
2. Lists of websites/ips must be included in the binary. Not a problem with docker, but binaries must include. [I think it's totally doable](https://stackoverflow.com/a/65148366).

**Comment by erkexzcx** [comment]
> In near future, could one of these options be useful? I think so.
> 
> -dos_list="gov,mil,oligarch"
> -dos_name="sberbank,gazprom"

Long story short - no, I will not do this. The point of this application that it is extremelly easy to use - no cofiguration, no reading, just run & forget...and also update time to time.

Adding external configuration files makes it more cumbersome and might scare a few users. I want this app to be as noob-friendly as possible.

Also if you use Visual Studio Code app (I do), you will get error once duplicate keys are found (the reason why I swapped slice (array) to map). Also my bad that I am not that good at writting Go tests and auto detecting these mistakes.

**Comment by baylanger** [comment]
I was seeing -dos_list / -dos_name as optional to overwrite the default (all sites).  I'm sure this coming Monday, an IT army might want to focus mainly on the stock market and the banks.

**Pull request closed without merging**
