### PR TITLE
Add embassies

### PR DESCRIPTION
**Pull request by jerzybrzoska**
Russian embassies in some not-aligned with NATO countries.

### CODE REVIEW

**Comment by baylanger** [comment]
This might not be the best thing to do.

Should we add only montreal & belarus ?  @jerzybrzoska @deputinizer do we have logic to remove de-dup destination?!  If so, we should put all of them, otherwise just keep 2 of them?!?!

Out of all the hostname in the PR, only 4 IPs are behind those.

```
194.85.30.164  <= montreal.mid.ru
93.157.56.164  <= montreal.mid.ru
194.85.30.83   <= belarus.mid.ru
93.157.56.83   <= belarus.mid.ru
```

Full output:
```
montreal.mid.ru is an alias for web164.mid.ru.
web164.mid.ru has address 93.157.56.164
web164.mid.ru has address 194.85.30.164
afghanistan.mid.ru is an alias for ptcus-4.mid.ru.
ptcus-4.mid.ru has address 194.85.30.83
ptcus-4.mid.ru has address 93.157.56.83
armenia.mid.ru is an alias for ptcus-4.mid.ru.
ptcus-4.mid.ru has address 93.157.56.83
ptcus-4.mid.ru has address 194.85.30.83
azerbaijan.mid.ru is an alias for ptcus-4.mid.ru.
ptcus-4.mid.ru has address 194.85.30.83
ptcus-4.mid.ru has address 93.157.56.83
beijing.mid.ru is an alias for ptcus-4.mid.ru.
ptcus-4.mid.ru has address 93.157.56.83
ptcus-4.mid.ru has address 194.85.30.83
belarus.mid.ru is an alias for ptcus-4.mid.ru.
ptcus-4.mid.ru has address 194.85.30.83
ptcus-4.mid.ru has address 93.157.56.83
cuba.mid.ru is an alias for ptcus-4.mid.ru.
ptcus-4.mid.ru has address 93.157.56.83
ptcus-4.mid.ru has address 194.85.30.83
georgia.mid.ru is an alias for ptcus-4.mid.ru.
ptcus-4.mid.ru has address 194.85.30.83
ptcus-4.mid.ru has address 93.157.56.83
helsinki.mid.ru is an alias for web164.mid.ru.
web164.mid.ru has address 194.85.30.164
web164.mid.ru has address 93.157.56.164
india.mid.ru is an alias for ptcus-4.mid.ru.
ptcus-4.mid.ru has address 93.157.56.83
ptcus-4.mid.ru has address 194.85.30.83
iran.mid.ru is an alias for ptcus-4.mid.ru.
ptcus-4.mid.ru has address 194.85.30.83
ptcus-4.mid.ru has address 93.157.56.83
mexico.mid.ru is an alias for ptcus-4.mid.ru.
ptcus-4.mid.ru has address 93.157.56.83
ptcus-4.mid.ru has address 194.85.30.83
moldova.mid.ru is an alias for web164.mid.ru.
web164.mid.ru has address 93.157.56.164
web164.mid.ru has address 194.85.30.164
mongolia.mid.ru is an alias for web164.mid.ru.
web164.mid.ru has address 194.85.30.164
web164.mid.ru has address 93.157.56.164
syria.mid.ru is an alias for ptcus-4.mid.ru.
ptcus-4.mid.ru has address 194.85.30.83
ptcus-4.mid.ru has address 93.157.56.83
sweden.mid.ru is an alias for web164.mid.ru.
web164.mid.ru has address 93.157.56.164
web164.mid.ru has address 194.85.30.164
turkmenistan.mid.ru is an alias for web164.mid.ru.
web164.mid.ru has address 194.85.30.164
web164.mid.ru has address 93.157.56.164
uzbekistan.mid.ru is an alias for ptcus-4.mid.ru.
ptcus-4.mid.ru has address 93.157.56.83
ptcus-4.mid.ru has address 194.85.30.83
```

**Comment by jerzybrzoska** [comment]
You are right it is better not to clutter needlessly this file and keep only two embassies. Apologies for not doing due diligence with `host` before opening this PR. I would edit the file once there is an agreement about this from @erkexzcx and the contributors.

**Comment by erkexzcx** [comment]
Yes, would be better if you change to those 2 domains only:
```
194.85.30.164  <= montreal.mid.ru
93.157.56.164  <= montreal.mid.ru
194.85.30.83   <= belarus.mid.ru
93.157.56.83   <= belarus.mid.ru
```

**Review by jerzybrzoska — COMMENTED** [review]
Done.

**Pull request merged**
