### PR TITLE
Add VPN compose example for reference

### PR DESCRIPTION
**Pull request by 6ftClaud**

### CODE REVIEW

**Comment by erkexzcx** [comment]
How is this going to help? Is this suppossed to be run on the same machine or what is the purpose of this?

**Comment by 6ftClaud** [comment]
This is an example config to route container traffic via a VPN as you made a point of using a VPN but did not include pointers as to how to do so.

**Comment by erkexzcx** [comment]
The point is to use VPN, such as NordVPN, for DOS traffic those websites so your VPN is hidden.

It's not for accessing http server of StopPropaganda via VPN.

**Comment by 6ftClaud** [comment]
It does use VPN to DOS

The rules in the comments are to enable access from your LAN to the website.

**Pull request closed without merging**
