### PR TITLE
Add lukoil remote management desktop

### PR DESCRIPTION
**Pull request by kopach**
From IT Army of Ukraine

### CODE REVIEW

**Comment by erkexzcx** [comment]
I thought it does not have web ports?

**Comment by erkexzcx** [comment]
It's actually hard to check since those servers already pretty much dead since their announcements. 😂

**Comment by kopach** [comment]
true 👍 . Anyway, it has web port, it's easy to check via search engine cache e.g. https://duckduckgo.com/?t=ffab&q=https%3A%2F%2Faaa-srt-apps.lukoil.com&ia=web
So, let's add those

**Comment by kopach** [comment]
google cache also shows their web page (at least, that it was there) - https://webcache.googleusercontent.com/search?q=cache:iY8m4GTYHucJ:https://aaa-srt-apps.lukoil.com/+&cd=1&hl=uk&ct=clnk&gl=pl&client=firefox-b-d

**Comment by GloryOfUkraine** [comment]
> It's actually hard to check since those servers already pretty much dead since their announcements. 😂

that is awesome!

**Pull request merged**
