### PR TITLE
More to block sberbank

### PR DESCRIPTION
**Pull request by jerzybrzoska**

### CODE REVIEW

**Comment by erkexzcx** [comment]
Can you update this MR so there is no conflict? Also please do not reorder anything as it makes difficult to review.

**Comment by jerzybrzoska** [comment]
I think I removed the conflict. But apologies if I did screw this up - I'm a newbie when it comes to git.

**Comment by erkexzcx** [comment]
image

**Comment by jerzybrzoska** [comment]
Apologies - I got lost and don't know what to do now with this PR.

**Comment by erkexzcx** [comment]
Let's just close it? :)

**Pull request closed without merging**
